import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const b = JSON.parse(fs.readFileSync(path.join(root, 'business.json'), 'utf8'));
const out = path.join(root, 'dist');
fs.mkdirSync(out, { recursive: true });
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const email = `<a href="mailto:${esc(b.email)}">${esc(b.email)}</a>`;
const phone = `<a href="tel:${esc(b.phoneLink)}">${esc(b.phone)}</a>`;
const policies = [
  ['terms.html', 'Terms & conditions'],
  ['privacy.html', 'Privacy policy'],
  ['refunds.html', 'Refunds & cancellations'],
  ['delivery.html', 'Service delivery']
];

const layout = (title, description, body, current = '') => `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${esc(title)} | ${esc(b.name)}</title>
  <meta name="description" content="${esc(description)}">
  <meta name="theme-color" content="#243acb">
  <link rel="icon" type="image/svg+xml" href="favicon.svg">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <a class="skip" href="#main">Skip to content</a>
  <header class="header wrap">
    <a href="index.html" class="brand" aria-label="Surecomply Services home"><span class="mark" aria-hidden="true">S</span><span>Surecomply<span class="brand-sub">Services</span></span></a>
    <nav aria-label="Main navigation">
      <a href="services.html"${current === 'services' ? ' aria-current="page"' : ''}>Services & pricing</a>
      <a href="contact.html"${current === 'contact' ? ' aria-current="page"' : ''}>Contact us</a>
    </nav>
  </header>
  <main id="main">${body}</main>
  <footer class="footer">
    <div class="wrap footer-grid">
      <div><a href="index.html" class="footer-brand">${esc(b.name)}</a><p>Websites, documents, and digital design.</p><p>${email}<br>${phone}</p></div>
      <nav aria-label="Company links"><span class="footer-label">Company</span><a href="index.html#about">About us</a><a href="services.html">Services & pricing</a><a href="contact.html">Contact us</a></nav>
      <nav aria-label="Policies"><span class="footer-label">Policies</span>${policies.map(([url, label]) => `<a href="${url}">${label}</a>`).join('')}</nav>
    </div>
    <div class="wrap copyright">© 2026 ${esc(b.name)}. All rights reserved.</div>
  </footer>
</body>
</html>`;

const serviceCards = `<div class="service-grid">
  <article class="service"><span class="number">01 / WEB</span><h3>Website setup</h3><p>Simple business websites and landing pages that explain what you do and make it easy to contact you.</p><ul><li>Responsive page layout</li><li>Business content placement</li><li>Basic website updates</li></ul></article>
  <article class="service"><span class="number">02 / DOCUMENTS</span><h3>Document formatting</h3><p>Clear, consistent formatting for the business documents and presentations you already have.</p><ul><li>Document layout and styling</li><li>Presentation formatting</li><li>PDF-ready file preparation</li></ul></article>
  <article class="service"><span class="number">03 / DESIGN</span><h3>Digital design</h3><p>Practical visual assets for your business communications and online presence.</p><ul><li>Social media graphics</li><li>Digital flyers and banners</li><li>Resizing and content updates</li></ul></article>
</div>`;

const home = `<section class="hero wrap">
  <div class="hero-copy"><p class="eyebrow">DIGITAL SERVICES, CLEARLY DEFINED</p><h1>A clearer digital<br>presence starts here.</h1><p class="lead">Website setup, document formatting, and digital design for your next business project.</p><div class="actions"><a class="button" href="contact.html">Discuss your project</a><a class="text-link" href="services.html">Explore services</a></div></div>
  <aside class="project-panel" aria-label="Our project approach"><p class="eyebrow">YOUR PROJECT, IN FOCUS</p><div class="panel-row"><span>01</span><div><h2>A defined scope</h2><p>Agree on exactly what needs to be made.</p></div></div><div class="panel-row"><span>02</span><div><h2>A written quote</h2><p>Know the price and delivery plan before work begins.</p></div></div><div class="panel-row"><span>03</span><div><h2>A digital handover</h2><p>Receive the deliverables agreed for your project.</p></div></div><div class="panel-bottom">ONE PROJECT. A CLEAR PLAN.</div></aside>
</section>
<section class="section services-section"><div class="wrap"><div class="section-head"><div><p class="eyebrow">WHAT WE CAN HELP WITH</p><h2>Three practical services.</h2></div><a class="text-link" href="services.html">View scope & pricing</a></div>${serviceCards}</div></section>
<section class="section wrap about" id="about"><div><p class="eyebrow">ABOUT SURECOMPLY SERVICES</p><h2>Focused on the details<br>of your digital work.</h2></div><div><p>Surecomply Services provides project-based digital services for business websites, documents, and visual communication. Each engagement starts with your requirements and a written agreement on the work to be delivered.</p><p>Our services are digital and delivered remotely. The scope, price, timing, file formats, and revision allowance are agreed before work begins.</p><a class="text-link" href="contact.html">Talk through your requirements</a></div></section>
<section class="wrap endnote"><div><h2>Have a project in mind?</h2><p>Send a brief description of what you need. We’ll discuss the scope before quoting.</p></div><a class="button" href="mailto:${esc(b.email)}">Email us</a></section>`;

const services = `<section class="wrap page-heading"><p class="eyebrow">SERVICES & PRICING</p><h1>Choose the help<br>your project needs.</h1><p class="lead">Each project is quoted individually in Indian rupees (INR). The final price depends on the agreed scope, complexity, and deliverables.</p></section><section class="wrap">${serviceCards}</section><section class="wrap section two-col"><div><h2>How pricing works</h2><p>Share your requirements by email or phone. We will confirm the deliverables and provide a written quote before you decide to proceed.</p><p>The quote sets out the total price, any applicable taxes, payment schedule, revisions, and delivery timeline. Additional work or third-party costs require your agreement.</p><a class="button" href="contact.html">Request a quote</a></div><div class="info-box"><h2>Included in your project agreement</h2><ul><li>The pages, files, or designs to be delivered</li><li>File formats and handover method</li><li>The price and payment milestones</li><li>A delivery date or schedule</li><li>The number of included revisions</li></ul><p>Domain registration, hosting, paid software, printing, and ongoing maintenance are included only when explicitly listed in your quote.</p></div></section><section class="wrap section prose"><h2>Before you order</h2><p>Review our <a href="terms.html">terms</a>, <a href="delivery.html">delivery policy</a>, and <a href="refunds.html">refund and cancellation policy</a>. These digital services do not include legal advice, statutory filings, or government approvals.</p></section>`;

const contact = `<section class="wrap page-heading"><p class="eyebrow">CONTACT US</p><h1>Let’s talk about<br>your project.</h1><p class="lead">For a quote, an existing project, or a cancellation or refund request, contact Surecomply Services using the details below.</p></section><section class="wrap contact-grid"><div class="contact-card"><span class="eyebrow">EMAIL</span><h2>${email}</h2><p>Send your requirements or include your project reference for support.</p></div><div class="contact-card"><span class="eyebrow">PHONE</span><h2>${phone}</h2><p>Discuss your requirements directly with us.</p></div>${b.address ? `<div class="contact-card address"><span class="eyebrow">BUSINESS ADDRESS</span><h2>${esc(b.name)}</h2><address>${esc(b.address).replace(/\n/g, '<br>')}</address></div>` : ''}</section><section class="wrap section prose"><h2>What to include in an enquiry</h2><p>Tell us which service you need, the deliverables you have in mind, and your preferred deadline. Please do not email passwords, payment card information, or unnecessary identity documents.</p></section>`;

const policy = (label, headline, html) => `<section class="wrap page-heading policy-heading"><p class="eyebrow">${label}</p><h1>${headline}</h1><p class="updated">Last updated: ${esc(b.updated)}</p></section><article class="wrap prose policy-body">${html}<div class="policy-contact"><h2>Contact</h2><p>${esc(b.name)}<br>Email: ${email}<br>Phone: ${phone}${b.address ? `<br>Address: ${esc(b.address).replace(/\n/g, '<br>')}` : ''}</p></div></article>`;

const terms = policy('OUR TERMS', 'Terms & conditions', `<p>These terms apply to the digital services provided by Surecomply Services and to the use of this website. Please read them together with the written quote or project agreement and the policies linked below.</p><h2>1. Scope of services</h2><p>We offer website setup, document formatting, and digital design. The specific deliverables, file formats, revisions, fees, and timeline for each project are set out in a written quote or project agreement accepted by you before work starts.</p><h2>2. Quotes and payments</h2><p>Prices are quoted in INR. The quote identifies any applicable taxes, additional costs, payment schedule, and validity period. We obtain your agreement before performing work outside the accepted scope or incurring additional charges. Payment instructions are provided with the accepted quote or invoice.</p><h2>3. Client materials and approvals</h2><p>You are responsible for supplying accurate information and materials that you are entitled to use. Please obtain any permissions needed for text, logos, photos, or other assets. Delays in materials, feedback, or approvals may affect the delivery schedule; any revised timeline will be communicated.</p><h2>4. Revisions and handover</h2><p>The quote specifies the included revisions. New requirements and revisions outside that allowance are quoted separately. The final formats and handover arrangements follow the accepted scope and our <a href="delivery.html">service delivery policy</a>.</p><h2>5. Ownership and third-party services</h2><p>Your existing content remains yours. The project agreement specifies the rights granted in final deliverables after payment. Third-party fonts, images, software, platforms, and other licensed materials remain subject to their own terms. Any paid third-party service must be agreed separately.</p><h2>6. Cancellations and refunds</h2><p>Requests are handled under our <a href="refunds.html">refund and cancellation policy</a>. Contact us with the project reference and reason for the request.</p><h2>7. Service limitations</h2><p>We do not guarantee sales, search rankings, payment gateway approval, or approval by any third party. These services do not include legal advice, regulatory certification, or government representation.</p><h2>8. Privacy and concerns</h2><p>Our <a href="privacy.html">privacy policy</a> explains the handling of enquiry and project information. If you have a concern, contact us so we can review it and work toward a resolution. Nothing in these terms excludes rights that cannot lawfully be excluded.</p><h2>9. Updates</h2><p>Updates to these website terms will be shown with a revised date. Material changes to an existing project require agreement and do not automatically change an accepted quote.</p>`);

const refunds = policy('CUSTOMER POLICY', 'Refunds & cancellations', `<p>This policy covers project-based digital services purchased from Surecomply Services.</p><h2>How to request a cancellation or refund</h2><p>Email ${email} with your project reference, payment details sufficient to identify the payment, and the reason for your request. Do not send full card numbers or account passwords.</p><h2>Before work starts</h2><p>If you cancel before work begins, the service fee paid is eligible for a full refund. Any separately authorised third-party purchase is handled according to the terms disclosed before that purchase.</p><h2>After work starts</h2><p>If you cancel after work has begun, we will identify the work completed and costs already incurred under the agreed scope. The unused portion of your service fee is eligible for a refund. We will provide the calculation and explain any deductions.</p><h2>Incomplete or incorrect deliverables</h2><p>If a deliverable does not match the agreed scope, contact us with details. We will review the issue and offer correction within an agreed timeframe. If we cannot provide the agreed service, the undelivered portion is eligible for a refund.</p><h2>Refund processing</h2><p>We will communicate the outcome of your request by email. Approved refunds are initiated within 7 business days to the original payment method where available. The time for the credit to appear depends on the payment provider and your bank.</p><h2>Third-party costs</h2><p>Domain names, hosting, paid assets, and software licences are purchased only with your prior agreement. Their cancellation and refund eligibility depend on the relevant provider’s terms disclosed at the time of purchase.</p><h2>Your rights</h2><p>This policy does not limit any refund or consumer rights available under applicable law.</p>`);

const delivery = policy('DELIVERY POLICY', 'Digital service delivery', `<p>Surecomply Services provides digital services remotely. No physical products are shipped under these service offerings.</p><h2>Delivery timeline</h2><p>The estimated completion date or project milestones are agreed in writing before work begins. Timing depends on the project scope, receipt of any agreed payment, access to necessary materials, and your feedback or approvals.</p><h2>How deliverables are provided</h2><p>Final deliverables are sent by email, a download link, or another delivery method agreed in the quote. Website projects may include a source-file handover or deployment to an account you control, as specified in the scope. The quote identifies the file formats and whether editable source files are included.</p><h2>Review and revisions</h2><p>You can review the deliverables against the agreed scope. Included revisions and any review period are specified in your project agreement. Work beyond the agreed scope requires an additional quote and your acceptance.</p><h2>Delays</h2><p>We will communicate any known delay and discuss a revised schedule. Delays in your materials, access, or feedback may change the timeline. If we cannot complete the agreed service, the <a href="refunds.html">refund and cancellation policy</a> applies.</p><h2>Access problems</h2><p>If you cannot open or download a delivered file, contact ${email} with your project reference so we can help with delivery.</p>`);

const privacy = policy('PRIVACY', 'Privacy policy', `<p>This policy explains how Surecomply Services handles information associated with this website, enquiries, and digital service projects.</p><h2>Information we receive</h2><p>When you contact us, we may receive your name, contact details, project requirements, correspondence, and files you choose to share. When you purchase a service, we may keep invoice and transaction-reference information needed to manage the engagement.</p><h2>How information is used</h2><p>We use this information to respond to enquiries, prepare quotes, carry out agreed work, deliver files, provide support, manage refunds, and meet applicable record-keeping obligations. Please provide only information relevant to your project.</p><h2>Website data and cookies</h2><p>This website has no enquiry form, customer account, advertising trackers, or analytics scripts added by Surecomply Services. The hosting provider may process technical information, such as IP addresses and request logs, to serve and protect the website.</p><h2>Service providers and payments</h2><p>Email, hosting, file-delivery, and payment providers may process information needed to provide their services under their own privacy terms. If a third-party payment page is used, payment credentials are entered with that provider. We do not request full card details, banking passwords, or one-time passwords by email or phone.</p><h2>Project materials</h2><p>Project files are used for the agreed service. We do not publish client materials as portfolio work without permission. Please avoid sending sensitive personal information unless it is necessary for the agreed work.</p><h2>Retention and security</h2><p>We retain information for the project, related support, and applicable legal or accounting obligations. We take reasonable measures to restrict access and protect the information we handle. No method of transmission or storage can be guaranteed completely secure.</p><h2>Your requests</h2><p>You may contact ${email} to ask about your information, request corrections, or request deletion where applicable. Some records may need to be retained to meet legal obligations or resolve an ongoing matter.</p><h2>Policy changes</h2><p>Changes will be published on this page with an updated date.</p>`);

const pages = [
 ['index.html', 'Digital services for your business', 'Website setup, document formatting, and digital design from Surecomply Services. Contact us for a project quote.', home, 'home'],
 ['services.html', 'Services & pricing', 'Explore website setup, document formatting, digital design, and quote-based pricing.', services, 'services'],
 ['contact.html', 'Contact us', 'Contact Surecomply Services for project enquiries, customer support, cancellations, and refunds.', contact, 'contact'],
 ['terms.html', 'Terms & conditions', 'Terms for digital services provided by Surecomply Services.', terms],
 ['privacy.html', 'Privacy policy', 'How Surecomply Services handles enquiry and project information.', privacy],
 ['refunds.html', 'Refunds & cancellations', 'Cancellation eligibility and refund processing for Surecomply Services digital projects.', refunds],
 ['delivery.html', 'Service delivery', 'Delivery methods and timelines for Surecomply Services digital work.', delivery]
];
for (const [filename, title, description, body, current] of pages) fs.writeFileSync(path.join(out, filename), layout(title, description, body, current));
fs.copyFileSync(path.join(root, 'styles.css'), path.join(out, 'styles.css'));
fs.writeFileSync(path.join(out, 'favicon.svg'), '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#243acb"/><text x="32" y="46" text-anchor="middle" font-family="Arial,sans-serif" font-weight="700" font-size="42" fill="white">S</text></svg>');
fs.writeFileSync(path.join(out, '404.html'), layout('Page not found', 'This page could not be found.', '<section class="wrap page-heading"><p class="eyebrow">404</p><h1>Page not found.</h1><p>This page may have moved.</p><a class="button" href="/">Go to home page</a></section>'));
fs.writeFileSync(path.join(out, 'robots.txt'), 'User-agent: *\nAllow: /\n');
console.log(`Built ${pages.length + 1} pages. Business location: ${b.address || 'awaiting owner input'}.`);
